### ISSUE TITLE
Standardise the titles for portal Dat sites

### ISSUE THREAD

**Issue by saulhardman** [Rotonde/user#7]
Whilst I'm journeying down the rabbit hole with regards to seeding I thought it worth mentioning the topic of standardising the titles of portals.

Currently my Beaker library looks like this:

<img width="244" alt="beaker-library" src="https://user-images.githubusercontent.com/578381/31743655-2058141a-b45c-11e7-9d7c-660817771e68.png">

It's kind of hard to tell what's what and who's who among the Rotonde portals.

Might it be wise to create a standard title format? E.g. `Rotonde Portal ([@/~]portal-name)`?

**Comment by ghost** [comment]
that's a BeakerBrowser issue for sure -- not able to change name (or even alias) of saved archive

**Comment by saulhardman** [comment]
No, but we can change the titles of our own, which I presume will then propagate?

**Comment by neauoire** [comment]
Yes, as the dat.json file is what is being queries on getInfo().

**Comment by frozenpandaman** [comment]
@pfrazee, any way Beaker Browser could eventually support setting local names/"nicknames" for read-only sites in the Library?

**Comment by pfrazee** [comment]
@frozenpandaman Yeah I think so. Tara and I are talking about it for 0.8.

**Comment by frozenpandaman** [comment]
Awesome. :)
